import Image from "next/image";
import { cn } from "@/lib/utils";

/**
 * The ToughBubble logo, sized by `className` (set a height, e.g. "h-5 w-auto").
 * By default both theme variants render and CSS shows the right one, so the
 * theme is never needed on the server and switching themes shows no gap.
 * `disc` shows the logo on its black disc instead, which reads in both themes.
 * Decorative: it always sits next to the "ToughBubble" wordmark. Images are
 * generated by `npm run brand:generate`.
 */
export function AppLogo({ className, disc = false }: { className?: string; disc?: boolean }) {
  if (disc) {
    return (
      <Image
        src="/brand/logo-disc.png"
        alt=""
        aria-hidden
        width={240}
        height={240}
        loading="eager"
        className={className}
      />
    );
  }
  const shared = { "aria-hidden": true, width: 350, height: 400, loading: "eager" } as const;
  return (
    <>
      <Image src="/brand/logo-light.png" alt="" {...shared} className={cn("dark:hidden", className)} />
      <Image src="/brand/logo-dark.png" alt="" {...shared} className={cn("hidden dark:block", className)} />
    </>
  );
}
